name: Build a release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build the project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.0
          target: esp32
          path: .

      - name: Merge the build artifacts
        uses: actions/upload-artifact@v2
        with:
          esp_idf_version: v5.0
          target: esp32
          command: python scripts/pack_firmware.py

      - name: Release the build artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "images/*.bin,build/*.bin"
          allowUpdates: true
          artifactErrorsFailBuild: true
